# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20160131_0406'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='"profiles"',
        ),
    ]
