# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 06:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20160203_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
