# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_auto_20160204_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dollars_earned',
            field=models.FloatField(default=0.0),
        ),
    ]
