# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncomment',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
