# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_userupvotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserUpvotes',
            new_name='UserUpvote',
        ),
    ]
