# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20160203_0416'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tag',
            table='"tags"',
        ),
    ]
